python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\01GENSR.sfm xml\collation\01_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\02EXOSR.sfm xml\collation\02_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\03LEVSR.sfm xml\collation\03_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\04NUMSR.sfm xml\collation\04_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\05DEUSR.sfm xml\collation\05_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\06JOSSR.sfm xml\collation\06_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\07JDGSR.sfm xml\collation\07_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\081SASR.sfm xml\collation\08_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\092SASR.sfm xml\collation\09_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\101KISR.sfm xml\collation\10_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\112KISR.sfm xml\collation\11_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\12ISASR.sfm xml\collation\12_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\13JERSR.sfm xml\collation\13_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\14EZKSR.sfm xml\collation\14_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\15HOSSR.sfm xml\collation\15_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\16JOLSR.sfm xml\collation\16_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\17AMOSR.sfm xml\collation\17_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\18OBASR.sfm xml\collation\18_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\19JONSR.sfm xml\collation\19_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\20MICSR.sfm xml\collation\20_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\21NAMSR.sfm xml\collation\21_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\22HABSR.sfm xml\collation\22_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\23ZEPSR.sfm xml\collation\23_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\24HAGSR.sfm xml\collation\24_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\25ZECSR.sfm xml\collation\25_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\26MALSR.sfm xml\collation\26_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\27PSASR.sfm xml\collation\27_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\28PROSR.sfm xml\collation\28_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\29JOBSR.sfm xml\collation\29_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\30SNGSR.sfm xml\collation\30_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\31RUTSR.sfm xml\collation\31_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\32LAMSR.sfm xml\collation\32_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\33ECCSR.sfm xml\collation\33_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\34ESTSR.sfm xml\collation\34_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\35DANSR.sfm xml\collation\35_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\36EZRSR.sfm xml\collation\36_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\37NEHSR.sfm xml\collation\37_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\381CHSR.sfm xml\collation\38_SR_collation.xml
python py\convert_tei_to_usfm.py -a vocalic -a orthographic -o usfm\392CHSR.sfm xml\collation\39_SR_collation.xml